[package]
name = "znak-bin"
version = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "znak"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.31", features = ["derive", "wrap_help"] }
clio = { version = "0.3.5", features = ["clap-parse"] }
serde_json = "1.0.139"
znak-lang = { path = ".." }
