stages:
  - test
  - deploy
  - publish

image: homebrew/brew
before_script:
  - brew install node
  - brew install oven-sh/bun/bun
  - npm set registry "https://npm.zerolimits.dev"
  - echo "//npm.zerolimits.dev/:_authToken=\"$NPM_AUTH_TOKEN\"" > .npmrc
  - bun pm whoami

test_job:
  stage: test
  script:
    - bun install
    - bun test

deploy_job:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG != /^v?\d+\.\d+\.\d+$/'
  before_script:
    - brew install flyctl
  script:
    - fly deploy

publish_job:
  stage: publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - bun publish
