stages:
  - test
  - prepare
  - release
  - publish

test_job:
  stage: test
  image: oven/bun
  script:
    - bun install
    - bun test

publish_job:
  stage: publish
  image: oven/bun
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - bun install --frozen-lockfile
    - bunx jsr publish --token "$JSR_TOKEN"
