stages:
  - test
  - publish

image: homebrew/brew
before_script:
  - brew install node
  - brew install oven-sh/bun/bun
  - npm config set //registry.npmjs.org/:_authToken ${NPM_AUTH_TOKEN}
  - npm whoami
  - bun install

test_job:
  stage: test
  script:
    - bun test

publish_job:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - bun run build
    - npm publish
