stages:
  - test
  - publish

image: homebrew/brew
before_script:
  - brew install python
  - brew install oven-sh/bun/bun

test_job:
  stage: test
  script:
    - bun install
    - bun test

publish_job:
  stage: publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - bun install --frozen-lockfile
    - bunx jsr publish --token "$JSR_TOKEN"
