stages:
  - test
  - deploy

variables:
  PROJECT_NAME: znak
  TAP_REPO: noClaps/homebrew-tap

test:
  stage: test
  image: rust:latest
  script:
    - cargo test

# Create formula and publish to tap
deploy_formula:
  stage: deploy
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_TAG
    - when: manual
  script:
    - apk update && apk add git
    - git config --global user.name "GitLab CI"
    - git config --global user.email "gitlab-ci@example.com"

    # Clone tap repo using HTTPS with token and trigger workflow
    - git clone https://oauth2:${GITHUB_TOKEN}@github.com/${TAP_REPO}.git tap
    - cd tap
    - git tag $PROJECT_NAME-$CI_COMMIT_TAG -m "$CI_COMMIT_TAG"
    - git push --tags https://oauth2:${GITHUB_TOKEN}@github.com/${TAP_REPO}.git
