stages:
  - test
  - deploy
  - publish

image: homebrew/brew
before_script:
  - brew install node
  - brew install oven-sh/bun/bun
  - npm config set //registry.npmjs.org/:_authToken ${NPM_AUTH_TOKEN}
  - npm whoami

test_job:
  stage: test
  script:
    - bun install
    - bun test

deploy_job:
  stage: deploy
  allow_failure: true
  before_script:
    - brew install flyctl
  script:
    - fly deploy --config fly.toml --access-token $FLY_API_TOKEN

publish_job:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - bun run build
    - npm publish
