[package]
name = "znak-lang"
version = "0.15.1"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
highlight = { git = "https://gitlab.com/noClaps/highlight", version = "0.7.0" }
pulldown-latex = "0.7.1"
regex = "1.11.1"
serde = "1.0.219"
